# Generated by Django 2.1.8 on 2020-08-10 01:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_commentmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentModel',
            new_name='Comment',
        ),
    ]
